---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	plan(plan)
	retrieve(retrieve)
	generate(generate)
	critique(critique)
	finish(finish)
	human_approval(human_approval)
	publish(publish)
	__end__([<p>__end__</p>]):::last
	__start__ --> plan;
	critique -.-> finish;
	critique -.-> generate;
	finish --> human_approval;
	generate --> critique;
	human_approval -.-> __end__;
	human_approval -.-> publish;
	plan --> retrieve;
	retrieve --> generate;
	publish --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc


